### ISSUE TITLE
time-picker value is not updated inside Reactive Form Control

### ISSUE THREAD

**Issue by Robinson3034** [owsolutions/amazing-time-picker#43] opened 2018-01-23 05:29 UTC
I used time-picker inside Reactive form control ,Issue I faced after changing the time picker view value not updated in component

   <form [formGroup]="myform">
        <mat-form-field>
                  <input type="time"  matInput atp-time-picker name="FromTime" placeholder="Time IN"  formControlName="FromTime" required>
         </mat-form-field>
   </form>

**Comment by torabian** [comment] 2018-01-24 19:37
Can you provide us a little bit of more details, provide code that we can reproduce.

**Comment by bam-dreymers** [comment] 2018-01-29 22:20
In AtpDirective, inject the control as NgControl, the in the after-close subscription set the control's value.

`import { NgControl } from "@angular/forms";`
...
  constructor(
    public viewContainerRef: ViewContainerRef,
    private atp: AmazingTimePickerService,
    **private control: NgControl**
  ) {}
...
    timePickerFunction.afterClose().subscribe(retTime => {
      ele.value = retTime;
      **if (this.control && this.control.control) {
        this.control.control.setValue(retTime);
      }**
    });

**Comment by shanthece** [comment] 2018-01-31 10:54
having same issue in reactive forms, even after followed bam-dreymers answers

**Comment by torabian** [comment] 2018-02-28 21:08
I have merged the code since all builds are passing and there is no backward compatibility issue. 
This will be available after 1.5.0 version, probably by 03 of March, when we deploy to npm.

Please open a new issue, if you still having problems for this.

**Closed by torabian** 2018-02-28 21:08 UTC
Labels: bug, help wanted

**Comment by Beni90** [comment] 2018-03-29 12:31
Hi guys, just installed the time-picker and have this problem as well. Formfield value is not updated in the component.

When is this going to be fixed?

**Comment by ugogiordano87** [comment] 2018-07-12 10:39
@Beni90 you have two options to make it works: 

1. Applying the "atp-time-picker" directive to the input field, e.g.:

`<label for="time_picker" class="control-label">Time Picker</label><input id="time_picker" formControlName="time_picker" type="time">`

2. Setting the value of the corresponding form control. This is my case, where I had and input group (input field + button) and want to make both the input and the button opening the time-picker
